### ISSUE TITLE
Add a link to the extension repo in the readme

### ISSUE THREAD

**Issue by dorian-marchal** [g3rv4/refined.chat#2]
I keep landing on this repo instead of https://github.com/g3rv4/Taut :smile:

**Comment by g3rv4** [comment]
ha, sorry for the confusion... I have two repos:

* [taut.rocks](https://github.com/g3rv4/taut.rocks) (this one) is the one that has the site
* [Taut](https://github.com/g3rv4/Taut) is the one with the extension

What is exactly what you'd like me to do? add a README to this one linking to the extension? that would make perfect sense :)

**Comment by dorian-marchal** [comment]
> What is exactly what you'd like me to do? add a README to this one linking to the extension? that would make perfect sense :)

Exactly :+1: 

Taut does rock, by the way. :wink: 
Hope it will attract more users, soon.

**Comment by g3rv4** [comment]
done! I'm happy you like it... one thing you could do to help if you have a couple minutes, is writing a quick review about it on the store you downloaded it from (chrome / firefox / opera).

thanks for the kind words!
