### ISSUE TITLE
Option to remove Slackbot?

### ISSUE THREAD

**Issue by tommygebru** [g3rv4/refined.chat#4]
Ahh nevermind, thats what the Mute feature is for..

**Comment by tommygebru** [comment]
Can you make it so that reactions are inline with the Slack user's name + status/timestamp? 

Currently it layered above the messages themselves so its hard to read, harder still if its a reaction layered above emojis..

**Comment by g3rv4** [comment]
Hi Tommy!

Thanks for the suggestion :) this repository is for the site... the one for the extension is at https://github.com/g3rv4/Refined/issues

Feel free to create an issue. I don’t have lots of time to work on it, but if you wanted to implement it, I’d be happy to bounce ideas (I did what I could just with css rules, I think we’d need to also tweak the position of some DOM elements to make it happen).

But let’s continue the discussion there ;)
